// Production implementation-digest authority belongs to the compiler-visible core package.
use quote::ToTokens;
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet, VecDeque};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use syn::visit::{self, Visit};
use syn::visit_mut::{self, VisitMut};
use syn::{Attribute, File, Item, Macro, Meta, Path as SynPath};

const DIGEST_SCHEMA_VERSION: u32 = 1;
const DERIVATION_PATH: &str = "crates/specforge/src/ir/derivation.rs";
const STAGE_ROOTS: &[(&str, &str, &str)] = &[
    (
        "SOURCE",
        "crates/specforge/src/ir/source.rs",
        "source_rule_registry",
    ),
    (
        "EVIDENCE",
        "crates/specforge/src/ir/evidence.rs",
        "evidence_rule_registry",
    ),
    (
        "SEMANTIC",
        "crates/specforge/src/ir/semantic.rs",
        "semantic_rule_registry",
    ),
    (
        "INTENT",
        "crates/specforge/src/ir/intent.rs",
        "intent_rule_registry",
    ),
    (
        "ADAPTER",
        "crates/specforge/src/ir/adapters.rs",
        "adapter_rule_registry",
    ),
];

#[derive(Debug, Clone)]
struct SemanticNode {
    key: String,
    tokens: String,
    identifiers: BTreeSet<String>,
}

#[derive(Default)]
struct SemanticIndex {
    nodes: BTreeMap<String, SemanticNode>,
    identifiers: BTreeMap<String, BTreeSet<String>>,
    always: BTreeSet<String>,
}

#[derive(Default)]
struct ReferenceCollector {
    identifiers: BTreeSet<String>,
}

impl<'ast> Visit<'ast> for ReferenceCollector {
    fn visit_path(&mut self, path: &'ast SynPath) {
        if let Some(first) = path.segments.first() {
            let first = first.ident.to_string();
            if matches!(first.as_str(), "self" | "super" | "crate" | "Self") {
                if let Some(last) = path.segments.last() {
                    self.identifiers.insert(last.ident.to_string());
                }
            } else {
                self.identifiers.insert(first);
            }
        }
        visit::visit_path(self, path);
    }

    fn visit_macro(&mut self, invocation: &'ast Macro) {
        collect_macro_references(invocation.tokens.clone(), self);
        visit::visit_macro(self, invocation);
    }
}

fn main() {
    if let Err(error) = run() {
        panic!("production-semantic digest generation failed: {error}");
    }
}

fn run() -> Result<(), String> {
    self_test()?;
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR")
            .ok_or_else(|| "CARGO_MANIFEST_DIR is unavailable".to_string())?,
    );
    let repository_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            format!(
                "cannot derive the repository root from {}",
                manifest_dir.display()
            )
        })?;
    let derivation_path = repository_root.join(DERIVATION_PATH);
    let derivation_source = read_source(&derivation_path)?;
    let derivation_file = parse_source(DERIVATION_PATH, &derivation_source)?;
    let kernel_tokens = normalized_production_file(&derivation_file);
    let kernel_sha256 = sha256_hex(kernel_tokens.as_bytes());

    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("build.rs").display()
    );
    println!("cargo:rerun-if-changed={}", derivation_path.display());

    let mut generated = String::new();
    generated.push_str("// @generated by crates/specforge-core/build.rs; do not edit.\n");
    generated.push_str(&format!(
        "pub(crate) const PRODUCTION_SEMANTIC_DIGEST_SCHEMA_VERSION: u32 = {DIGEST_SCHEMA_VERSION};\n"
    ));
    generated.push_str(&format!(
        "pub(crate) const PRODUCTION_KERNEL_SEMANTIC_SHA256: &str = \"{kernel_sha256}\";\n"
    ));
    generated.push_str("#[cfg(test)] pub(crate) const PRODUCTION_SEMANTIC_INPUTS: &[&str] = &[\n");
    generated.push_str(&format!("    {:?},\n", DERIVATION_PATH));
    for (_, relative_path, _) in STAGE_ROOTS {
        generated.push_str(&format!("    {:?},\n", relative_path));
    }
    generated.push_str("];\n");

    for (stage, relative_path, root) in STAGE_ROOTS {
        let source_path = repository_root.join(relative_path);
        println!("cargo:rerun-if-changed={}", source_path.display());
        let source = read_source(&source_path)?;
        let file = parse_source(relative_path, &source)?;
        let index = SemanticIndex::from_file(&file)?;
        let closure = index.closure(root)?;
        let stage_sha256 = stage_digest(&kernel_sha256, relative_path, root, &closure);
        generated.push_str(&format!(
            "pub(crate) const {stage}_PRODUCTION_SEMANTIC_SHA256: &str = \"{stage_sha256}\";\n"
        ));
        generated.push_str(&format!(
            "#[cfg(test)] pub(crate) const {stage}_PRODUCTION_SEMANTIC_ITEMS: &[&str] = &[\n"
        ));
        for node in closure.values() {
            generated.push_str(&format!("    {:?},\n", node.key));
        }
        generated.push_str("];\n");
    }

    let output_dir =
        PathBuf::from(env::var_os("OUT_DIR").ok_or_else(|| "OUT_DIR is unavailable".to_string())?);
    fs::write(output_dir.join("production_semantic_digests.rs"), generated)
        .map_err(|error| format!("cannot write generated semantic digests: {error}"))?;
    Ok(())
}

fn read_source(path: &Path) -> Result<String, String> {
    fs::read_to_string(path).map_err(|error| format!("cannot read {}: {error}", path.display()))
}

fn parse_source(label: &str, source: &str) -> Result<File, String> {
    syn::parse_file(source).map_err(|error| format!("cannot parse {label}: {error}"))
}

impl SemanticIndex {
    fn from_file(file: &File) -> Result<Self, String> {
        let mut file = file.clone();
        ProductionSanitizer.visit_file_mut(&mut file);
        let mut index = Self::default();
        for item in &file.items {
            match item {
                Item::Fn(item) => index.insert(
                    format!("fn:{}", item.sig.ident),
                    item.sig.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Const(item) => index.insert(
                    format!("const:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Static(item) => index.insert(
                    format!("static:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Struct(item) => index.insert(
                    format!("struct:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Enum(item) => index.insert(
                    format!("enum:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Union(item) => index.insert(
                    format!("union:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Type(item) => index.insert(
                    format!("type:{}", item.ident),
                    item.ident.to_string(),
                    normalized_tokens(item),
                    item,
                )?,
                Item::Macro(item) if item.ident.is_some() => {
                    let ident = item.ident.as_ref().expect("checked macro identity");
                    index.insert(
                        format!("macro:{ident}"),
                        ident.to_string(),
                        normalized_tokens(item),
                        item,
                    )?;
                }
                Item::Use(item) => index.insert_use_item(item)?,
                _ => {}
            }
        }
        Ok(index)
    }

    fn insert_use_item(&mut self, item: &syn::ItemUse) -> Result<(), String> {
        let mut leaves = Vec::new();
        flatten_use_tree(Vec::new(), &item.tree, &mut leaves);
        let attributes = &item.attrs;
        let attributes = normalized_token_stream(quote::quote!(#(#attributes)*));
        let visibility = normalized_tokens(&item.vis);
        let leading_colon = if item.leading_colon.is_some() {
            "::"
        } else {
            ""
        };
        for leaf in leaves {
            let tokens = format!(
                "{attributes} {visibility} use {leading_colon}{};",
                leaf.binding
            );
            let key = format!("use:{}", sha256_hex(tokens.as_bytes()));
            let node = SemanticNode {
                key: key.clone(),
                tokens,
                identifiers: BTreeSet::new(),
            };
            if self.nodes.insert(key.clone(), node).is_some() {
                return Err(format!("duplicate semantic import node '{key}'"));
            }
            if let Some(exposed) = leaf.exposed {
                self.identifiers.entry(exposed).or_default().insert(key);
            } else {
                self.always.insert(key);
            }
        }
        Ok(())
    }

    fn insert<T: ToTokens + for<'ast> VisitTarget<'ast>>(
        &mut self,
        key: String,
        identifier: String,
        tokens: String,
        target: &T,
    ) -> Result<(), String> {
        let mut references = ReferenceCollector::default();
        target.visit_with(&mut references);
        let node = SemanticNode {
            key: key.clone(),
            tokens,
            identifiers: references.identifiers,
        };
        if self.nodes.insert(key.clone(), node).is_some() {
            return Err(format!("duplicate semantic node '{key}'"));
        }
        self.identifiers
            .entry(identifier)
            .or_default()
            .insert(key.clone());
        Ok(())
    }

    fn closure(&self, root: &str) -> Result<BTreeMap<String, SemanticNode>, String> {
        let roots = self
            .identifiers
            .get(root)
            .ok_or_else(|| format!("semantic root '{root}' is absent"))?;
        if roots.len() != 1 {
            return Err(format!(
                "semantic root '{root}' is ambiguous across {} nodes",
                roots.len()
            ));
        }
        let mut pending = VecDeque::from_iter(roots.iter().cloned());
        pending.extend(self.always.iter().cloned());
        let mut closure = BTreeMap::new();
        while let Some(key) = pending.pop_front() {
            if closure.contains_key(&key) {
                continue;
            }
            let node = self
                .nodes
                .get(&key)
                .ok_or_else(|| format!("semantic node '{key}' disappeared"))?
                .clone();
            for identifier in &node.identifiers {
                if let Some(dependencies) = self.identifiers.get(identifier) {
                    pending.extend(dependencies.iter().cloned());
                }
            }
            closure.insert(key, node);
        }
        Ok(closure)
    }
}

struct UseLeaf {
    exposed: Option<String>,
    binding: String,
}

fn flatten_use_tree(prefix: Vec<String>, tree: &syn::UseTree, leaves: &mut Vec<UseLeaf>) {
    match tree {
        syn::UseTree::Path(path) => {
            let mut prefix = prefix;
            prefix.push(path.ident.to_string());
            flatten_use_tree(prefix, &path.tree, leaves);
        }
        syn::UseTree::Name(name) => {
            let mut path = prefix;
            let name = name.ident.to_string();
            let exposed = if name == "self" {
                path.last().cloned()
            } else {
                path.push(name.clone());
                Some(name.clone())
            };
            if name == "self" {
                path.push(name);
            }
            leaves.push(UseLeaf {
                exposed,
                binding: path.join("::"),
            });
        }
        syn::UseTree::Rename(rename) => {
            let mut path = prefix;
            path.push(rename.ident.to_string());
            leaves.push(UseLeaf {
                exposed: Some(rename.rename.to_string()),
                binding: format!("{} as {}", path.join("::"), rename.rename),
            });
        }
        syn::UseTree::Glob(_) => leaves.push(UseLeaf {
            exposed: None,
            binding: if prefix.is_empty() {
                "*".to_string()
            } else {
                format!("{}::*", prefix.join("::"))
            },
        }),
        syn::UseTree::Group(group) => {
            for tree in &group.items {
                flatten_use_tree(prefix.clone(), tree, leaves);
            }
        }
    }
}

trait VisitTarget<'ast> {
    fn visit_with(&'ast self, visitor: &mut ReferenceCollector);
}

macro_rules! impl_visit_target {
    ($type:ty, $method:ident) => {
        impl<'ast> VisitTarget<'ast> for $type {
            fn visit_with(&'ast self, visitor: &mut ReferenceCollector) {
                visitor.$method(self);
            }
        }
    };
}

impl_visit_target!(syn::ItemFn, visit_item_fn);
impl_visit_target!(syn::ItemConst, visit_item_const);
impl_visit_target!(syn::ItemStatic, visit_item_static);
impl_visit_target!(syn::ItemStruct, visit_item_struct);
impl_visit_target!(syn::ItemEnum, visit_item_enum);
impl_visit_target!(syn::ItemUnion, visit_item_union);
impl_visit_target!(syn::ItemType, visit_item_type);
impl_visit_target!(syn::ItemMacro, visit_item_macro);

fn stage_digest(
    kernel_sha256: &str,
    relative_path: &str,
    root: &str,
    closure: &BTreeMap<String, SemanticNode>,
) -> String {
    let mut hasher = Sha256::new();
    frame(&mut hasher, b"specforge-production-semantic-closure");
    frame(&mut hasher, &DIGEST_SCHEMA_VERSION.to_be_bytes());
    frame(&mut hasher, kernel_sha256.as_bytes());
    frame(&mut hasher, relative_path.as_bytes());
    frame(&mut hasher, root.as_bytes());
    for node in closure.values() {
        frame(&mut hasher, node.key.as_bytes());
        frame(&mut hasher, sha256_hex(node.tokens.as_bytes()).as_bytes());
    }
    format!("{:x}", hasher.finalize())
}

fn normalized_production_file(file: &File) -> String {
    let mut file = file.clone();
    ProductionSanitizer.visit_file_mut(&mut file);
    let mut normalized = String::new();
    for item in &file.items {
        normalized.push_str(&normalized_tokens(item));
        normalized.push('\n');
    }
    normalized
}

fn item_attrs(item: &Item) -> &[Attribute] {
    match item {
        Item::Const(item) => &item.attrs,
        Item::Enum(item) => &item.attrs,
        Item::ExternCrate(item) => &item.attrs,
        Item::Fn(item) => &item.attrs,
        Item::ForeignMod(item) => &item.attrs,
        Item::Impl(item) => &item.attrs,
        Item::Macro(item) => &item.attrs,
        Item::Mod(item) => &item.attrs,
        Item::Static(item) => &item.attrs,
        Item::Struct(item) => &item.attrs,
        Item::Trait(item) => &item.attrs,
        Item::TraitAlias(item) => &item.attrs,
        Item::Type(item) => &item.attrs,
        Item::Union(item) => &item.attrs,
        Item::Use(item) => &item.attrs,
        _ => &[],
    }
}

fn is_test_only(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attribute| {
        attribute.path().is_ident("cfg")
            && attribute
                .parse_args::<Meta>()
                .is_ok_and(|meta| evaluate_production_cfg(&meta) == CfgTruth::False)
    })
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum CfgTruth {
    True,
    False,
    Unknown,
}

fn evaluate_production_cfg(meta: &Meta) -> CfgTruth {
    match meta {
        Meta::Path(path) if path.is_ident("test") => CfgTruth::False,
        Meta::Path(_) => CfgTruth::Unknown,
        Meta::NameValue(name_value) if name_value.path.is_ident("feature") => {
            let syn::Expr::Lit(expression) = &name_value.value else {
                return CfgTruth::Unknown;
            };
            let syn::Lit::Str(feature) = &expression.lit else {
                return CfgTruth::Unknown;
            };
            if matches!(
                feature.value().as_str(),
                "test-support" | "conformance-support"
            ) {
                CfgTruth::False
            } else {
                CfgTruth::Unknown
            }
        }
        Meta::NameValue(_) => CfgTruth::Unknown,
        Meta::List(list) => {
            use syn::parse::Parser;
            let parser = syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated;
            let Ok(arguments) = parser.parse2(list.tokens.clone()) else {
                return CfgTruth::Unknown;
            };
            let values = arguments
                .iter()
                .map(evaluate_production_cfg)
                .collect::<Vec<_>>();
            if list.path.is_ident("any") {
                if values.contains(&CfgTruth::True) {
                    CfgTruth::True
                } else if values.iter().all(|value| *value == CfgTruth::False) {
                    CfgTruth::False
                } else {
                    CfgTruth::Unknown
                }
            } else if list.path.is_ident("all") {
                if values.contains(&CfgTruth::False) {
                    CfgTruth::False
                } else if values.iter().all(|value| *value == CfgTruth::True) {
                    CfgTruth::True
                } else {
                    CfgTruth::Unknown
                }
            } else if list.path.is_ident("not") && values.len() == 1 {
                match values[0] {
                    CfgTruth::True => CfgTruth::False,
                    CfgTruth::False => CfgTruth::True,
                    CfgTruth::Unknown => CfgTruth::Unknown,
                }
            } else {
                CfgTruth::Unknown
            }
        }
    }
}

struct ProductionSanitizer;

impl VisitMut for ProductionSanitizer {
    fn visit_file_mut(&mut self, file: &mut File) {
        file.items.retain(|item| !is_test_only(item_attrs(item)));
        visit_mut::visit_file_mut(self, file);
    }

    fn visit_item_mod_mut(&mut self, item: &mut syn::ItemMod) {
        if let Some((_, items)) = &mut item.content {
            items.retain(|item| !is_test_only(item_attrs(item)));
        }
        visit_mut::visit_item_mod_mut(self, item);
    }

    fn visit_item_struct_mut(&mut self, item: &mut syn::ItemStruct) {
        match &mut item.fields {
            syn::Fields::Named(fields) => {
                fields.named = fields
                    .named
                    .clone()
                    .into_iter()
                    .filter(|field| !is_test_only(&field.attrs))
                    .collect();
            }
            syn::Fields::Unnamed(fields) => {
                fields.unnamed = fields
                    .unnamed
                    .clone()
                    .into_iter()
                    .filter(|field| !is_test_only(&field.attrs))
                    .collect();
            }
            syn::Fields::Unit => {}
        }
        visit_mut::visit_item_struct_mut(self, item);
    }

    fn visit_item_union_mut(&mut self, item: &mut syn::ItemUnion) {
        item.fields.named = item
            .fields
            .named
            .clone()
            .into_iter()
            .filter(|field| !is_test_only(&field.attrs))
            .collect();
        visit_mut::visit_item_union_mut(self, item);
    }

    fn visit_item_enum_mut(&mut self, item: &mut syn::ItemEnum) {
        item.variants = item
            .variants
            .clone()
            .into_iter()
            .filter(|variant| !is_test_only(&variant.attrs))
            .collect();
        visit_mut::visit_item_enum_mut(self, item);
    }

    fn visit_item_impl_mut(&mut self, item: &mut syn::ItemImpl) {
        item.items
            .retain(|member| !is_test_only(impl_item_attrs(member)));
        visit_mut::visit_item_impl_mut(self, item);
    }

    fn visit_item_trait_mut(&mut self, item: &mut syn::ItemTrait) {
        item.items
            .retain(|member| !is_test_only(trait_item_attrs(member)));
        visit_mut::visit_item_trait_mut(self, item);
    }

    fn visit_block_mut(&mut self, block: &mut syn::Block) {
        block
            .stmts
            .retain(|statement| !is_test_only(&outer_attributes(statement)));
        visit_mut::visit_block_mut(self, block);
    }

    fn visit_expr_match_mut(&mut self, expression: &mut syn::ExprMatch) {
        expression.arms.retain(|arm| !is_test_only(&arm.attrs));
        visit_mut::visit_expr_match_mut(self, expression);
    }
}

fn impl_item_attrs(item: &syn::ImplItem) -> &[Attribute] {
    match item {
        syn::ImplItem::Const(item) => &item.attrs,
        syn::ImplItem::Fn(item) => &item.attrs,
        syn::ImplItem::Type(item) => &item.attrs,
        syn::ImplItem::Macro(item) => &item.attrs,
        _ => &[],
    }
}

fn trait_item_attrs(item: &syn::TraitItem) -> &[Attribute] {
    match item {
        syn::TraitItem::Const(item) => &item.attrs,
        syn::TraitItem::Fn(item) => &item.attrs,
        syn::TraitItem::Type(item) => &item.attrs,
        syn::TraitItem::Macro(item) => &item.attrs,
        _ => &[],
    }
}

fn outer_attributes(value: &impl ToTokens) -> Vec<Attribute> {
    use syn::parse::{Parse, ParseStream};

    struct AttributePrefix(Vec<Attribute>);

    impl Parse for AttributePrefix {
        fn parse(input: ParseStream<'_>) -> syn::Result<Self> {
            let attributes = Attribute::parse_outer(input)?;
            while !input.is_empty() {
                let _: proc_macro2::TokenTree = input.parse()?;
            }
            Ok(Self(attributes))
        }
    }

    syn::parse2::<AttributePrefix>(value.to_token_stream())
        .map(|prefix| prefix.0)
        .unwrap_or_default()
}

fn normalized_tokens(value: &impl ToTokens) -> String {
    normalized_token_stream(value.to_token_stream())
}

fn normalized_token_stream(stream: proc_macro2::TokenStream) -> String {
    strip_nonsemantic_attributes(stream).to_string()
}

fn strip_nonsemantic_attributes(stream: proc_macro2::TokenStream) -> proc_macro2::TokenStream {
    use proc_macro2::{Group, TokenStream, TokenTree};
    let mut input = stream.into_iter().peekable();
    let mut output = TokenStream::new();
    while let Some(token) = input.next() {
        if matches!(&token, TokenTree::Punct(punct) if punct.as_char() == '#')
            && input.peek().is_some_and(attribute_is_nonsemantic)
        {
            input.next();
            continue;
        }
        match token {
            TokenTree::Group(group) => {
                let mut normalized = Group::new(
                    group.delimiter(),
                    strip_nonsemantic_attributes(group.stream()),
                );
                normalized.set_span(group.span());
                output.extend([TokenTree::Group(normalized)]);
            }
            other => output.extend([other]),
        }
    }
    output
}

fn attribute_is_nonsemantic(token: &proc_macro2::TokenTree) -> bool {
    let proc_macro2::TokenTree::Group(group) = token else {
        return false;
    };
    if group.delimiter() != proc_macro2::Delimiter::Bracket {
        return false;
    }
    let Ok(meta) = syn::parse2::<Meta>(group.stream()) else {
        return false;
    };
    if meta.path().is_ident("doc")
        || meta.path().is_ident("allow")
        || meta.path().is_ident("warn")
        || meta.path().is_ident("deny")
        || meta.path().is_ident("forbid")
        || meta.path().is_ident("expect")
        || meta.path().is_ident("rustfmt")
    {
        return true;
    }
    if meta.path().is_ident("cfg") {
        let Meta::List(list) = meta else {
            return false;
        };
        return syn::parse2::<Meta>(list.tokens)
            .is_ok_and(|condition| evaluate_production_cfg(&condition) == CfgTruth::True);
    }
    if meta.path().is_ident("cfg_attr") {
        let Meta::List(list) = meta else {
            return false;
        };
        use syn::parse::Parser;
        let parser = syn::punctuated::Punctuated::<Meta, syn::Token![,]>::parse_terminated;
        return parser
            .parse2(list.tokens)
            .ok()
            .and_then(|arguments| arguments.first().cloned())
            .is_some_and(|condition| evaluate_production_cfg(&condition) == CfgTruth::False);
    }
    false
}

fn collect_macro_references(stream: proc_macro2::TokenStream, references: &mut ReferenceCollector) {
    let expression_array = proc_macro2::TokenStream::from(proc_macro2::TokenTree::Group(
        proc_macro2::Group::new(proc_macro2::Delimiter::Bracket, stream.clone()),
    ));
    if let Ok(expressions) = syn::parse2::<syn::ExprArray>(expression_array) {
        references.visit_expr_array(&expressions);
        return;
    }
    collect_macro_call_identifiers(stream, &mut references.identifiers);
}

fn collect_macro_call_identifiers(
    stream: proc_macro2::TokenStream,
    identifiers: &mut BTreeSet<String>,
) {
    let tokens = stream.into_iter().collect::<Vec<_>>();
    for (index, token) in tokens.iter().enumerate() {
        if let proc_macro2::TokenTree::Ident(ident) = token
            && matches!(
                tokens.get(index + 1),
                Some(proc_macro2::TokenTree::Group(group))
                    if group.delimiter() == proc_macro2::Delimiter::Parenthesis
            )
        {
            identifiers.insert(ident.to_string());
        }
        if let proc_macro2::TokenTree::Group(group) = token {
            collect_macro_call_identifiers(group.stream(), identifiers);
        }
    }
}

fn frame(hasher: &mut Sha256, bytes: &[u8]) {
    hasher.update((bytes.len() as u64).to_be_bytes());
    hasher.update(bytes);
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn self_test() -> Result<(), String> {
    let baseline = parse_source(
        "self-test baseline",
        "use alpha::Token; struct Context { value: u8, #[cfg(test)] fixture: u8 } #[cfg(not(test))] fn root(value: Token) -> u8 { #[cfg(test)] { panic!(\"baseline fixture\"); } vec![helper(Context { value: value.into() }.value)][0] } fn helper(value: u8) -> u8 { value + 1 } fn unrelated() -> u8 { 7 }",
    )?;
    let inert = parse_source(
        "self-test inert",
        "use alpha::Token; use ignored::Thing; struct Context { value: u8, #[cfg(any(test, feature = \"test-support\"))] renamed_fixture: String } /// changed docs\n#[cfg_attr(test, deprecated)] fn root( value : Token )->u8 { #[cfg(feature = \"test-support\")] { panic!(\"changed fixture\"); } /* changed comment */ vec![helper(Context { value: value.into() }.value)][0] }\nfn helper(value:u8)->u8 { value + 1 }\nfn unrelated()->u8 { 99 }\n#[cfg(test)] fn fixture_only() { panic!(\"fixture\") }",
    )?;
    let semantic = parse_source(
        "self-test semantic",
        "use alpha::Token; struct Context { value: u8, #[cfg(test)] fixture: u8 } fn root(value: Token) -> u8 { #[cfg(test)] { panic!(\"fixture\"); } vec![helper(Context { value: value.into() }.value)][0] } fn helper(value: u8) -> u8 { value + 2 } fn unrelated() -> u8 { 7 }",
    )?;
    let rebound = parse_source(
        "self-test rebound import",
        "use beta::Token; struct Context { value: u8, #[cfg(test)] fixture: u8 } fn root(value: Token) -> u8 { #[cfg(test)] { panic!(\"fixture\"); } vec![helper(Context { value: value.into() }.value)][0] } fn helper(value: u8) -> u8 { value + 1 } fn unrelated() -> u8 { 7 }",
    )?;
    let baseline_index = SemanticIndex::from_file(&baseline)?;
    let inert_index = SemanticIndex::from_file(&inert)?;
    let semantic_index = SemanticIndex::from_file(&semantic)?;
    let rebound_index = SemanticIndex::from_file(&rebound)?;
    let baseline_closure = baseline_index.closure("root")?;
    let inert_closure = inert_index.closure("root")?;
    let semantic_closure = semantic_index.closure("root")?;
    let rebound_closure = rebound_index.closure("root")?;
    let digest = |closure: &BTreeMap<String, SemanticNode>| {
        stage_digest(&"0".repeat(64), "self-test.rs", "root", closure)
    };
    if digest(&baseline_closure) != digest(&inert_closure) {
        return Err(
            "comment/doc/format/test-only/unrelated-production mutation changed the closure digest"
                .to_string(),
        );
    }
    if digest(&baseline_closure) == digest(&semantic_closure) {
        return Err("production dependency mutation did not change the closure digest".to_string());
    }
    if digest(&baseline_closure) == digest(&rebound_closure) {
        return Err("referenced import rebinding did not change the closure digest".to_string());
    }
    if baseline_closure.keys().any(|key| key.contains("unrelated")) {
        return Err("unreferenced production item entered the semantic closure".to_string());
    }
    Ok(())
}
